[project]
name = "grm_export"
version = "2.0"
dependencies = [
    "aiohttp",
    "diskcache",
    "enlighten",
    "gpxpy",
    "mapbox-vector-tile",
    "pgeocode",
    "pydantic",
    "pydantic-settings",
    "pyproj",
    "rdp",
]